name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.10/18"

    - name: Install Requirements
      run: |
        pip install -r requirements.txt

    - name: Train Model
      run: |
        python training/train_dl_model.py
        python training/train_ml_model.py

    - name: Run Tests
      run: |
        pytest